name: Docker CD - Deploy to Server

on:
  workflow_run:
    workflows: ["Docker CI - Build & Push Images"] # Nama workflow CI Anda
    types:
      - completed # Hanya berjalan jika workflow CI selesai
    branches:
      - main # Hanya untuk branch main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    # Hanya deploy jika workflow CI yang memicunya berhasil
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository (jika butuh file dari repo, misal docker-compose.yml terbaru)
        uses: actions/checkout@v4
        with:
          # Mengambil commit yang sama dengan yang memicu workflow_run
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      
      - name: Deploy to Server
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_SERVER_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          APP_DIR: /home/ubuntu/fullstack-filament-nextjs # GANTI DENGAN PATH APLIKASI ANDA DI SERVER
          # Variabel untuk .env di server
          PROD_DB_USER_SECRET: ${{ secrets.PROD_DB_USER }}
          PROD_DB_PASSWORD_SECRET: ${{ secrets.PROD_DB_PASSWORD }}
          PROD_DB_NAME_SECRET: ${{ secrets.PROD_DB_NAME }}
          PROD_ADMIN_APP_URL_SECRET: ${{ secrets.PROD_ADMIN_APP_URL }}
          PROD_APP_KEY_SECRET: ${{ secrets.PROD_APP_KEY }}
          # Tambahkan secret lain jika perlu

        run: |
          echo "Deploying latest version to server ${{ env.DEPLOY_HOST }}..."
          COMMIT_SHA_SHORT=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)
          echo "Based on commit: $COMMIT_SHA_SHORT"

          ssh -o StrictHostKeyChecking=no ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "
            set -e # Script akan exit jika ada error

            echo 'Navigating to app directory...'
            cd ${{ env.APP_DIR }}

            echo 'Pulling latest code from Git repository (main branch)...'
            # Pastikan user SSH Anda memiliki akses ke repositori Git (misalnya via SSH key deploy)
            # atau jika repo publik, ini akan bekerja.
            # Jika Anda menggunakan branch lain untuk produksi, sesuaikan 'main'.
            git checkout main 
            git fetch origin main # Ambil perubahan terbaru tanpa langsung merge
            # git reset --hard origin/main # Paksa direktori kerja sama dengan remote (HATI-HATI: menghapus perubahan lokal di server)
            # Alternatif yang lebih aman jika ada perubahan manual di server yang ingin dijaga:
            git pull origin main

            echo 'Creating/Updating .env file for Docker Compose...'
            # ... (script echo untuk membuat .env tetap di sini) ...
            
            echo 'Pulling latest images (tagged as :latest from main branch)...'
            docker compose -f docker-compose.prod.yml pull # Gunakan 'docker compose' (tanpa strip) untuk versi terbaru

            echo 'Bringing up new containers...'
            docker compose -f docker-compose.prod.yml up -d --remove-orphans # Gunakan 'docker compose'

            echo 'Running Laravel migrations...'
            docker compose -f docker-compose.prod.yml exec admin-app-php php artisan migrate --force # Gunakan 'docker compose'

            echo 'Optimizing Laravel application...'
            docker compose -f docker-compose.prod.yml exec admin-app-php php artisan optimize:clear # Gunakan 'docker compose'
            docker compose -f docker-compose.prod.yml exec admin-app-php php artisan optimize # Gunakan 'docker compose'
            
            echo 'Deployment finished successfully!'
          "