name: Docker CI - Build & Push Images

# Kapan workflow ini akan berjalan
on:
  push:
    branches:
      - main # Ganti dengan branch utama Anda jika bukan 'main'
  pull_request:
    branches:
      - main # Ganti dengan branch utama Anda jika bukan 'main'

jobs:
  build_and_push_images:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      # (Opsional) Login ke Docker Hub atau registry lain
      # Hanya diperlukan jika Anda ingin 'push' image
      # Hapus atau komentari bagian ini jika Anda hanya ingin 'build'
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' # Hanya login jika push ke main
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Gunakan Personal Access Token

      # Build dan Push untuk admin-app-php (Laravel)
      - name: Build and push admin-app-php
        uses: docker/build-push-action@v6
        with:
          context: ./admin-app # Path ke konteks build untuk admin-app
          file: ./admin-app/Dockerfile # Path ke Dockerfile admin-app
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }} # Push hanya jika push ke main
          tags: | # Ganti 'your-dockerhub-username' dengan username Anda
            bluulabs/admin-app-php:latest
            bluulabs/admin-app-php:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build dan Push untuk client-app (Next.js)
      # Untuk Next.js, kita perlu meneruskan NEXT_PUBLIC_API_URL saat build
      - name: Build and push client-app
        uses: docker/build-push-action@v6
        with:
          context: ./client-app # Path ke konteks build untuk client-app
          file: ./client-app/Dockerfile # Path ke Dockerfile client-app
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }} # Push hanya jika push ke main
          tags: | # Ganti 'bluulabs' dengan username Anda
            bluulabs/client-app:latest
            bluulabs/client-app:${{ github.sha }}
          build-args: | # Argumen yang diteruskan saat build image Docker
            NEXT_PUBLIC_API_URL_ARG=${{ vars.PROD_NEXT_PUBLIC_API_URL || 'http://api.example.com' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max